# Generated by Django 4.1.6 on 2023-02-17 11:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('helpdesk', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='ticket',
            name='status',
            field=models.CharField(choices=[('Unassigned', 'Unasigned'), ('Assigned', 'Assigned'), ('Completed', 'Completed')], default='Unassigned', max_length=20),
        ),
    ]
