version: "3.8"
services:
  db:
    image: "postgres"
    ports:
      - "5432:5432"
    volumes:
      - c://pg:/var/lib/postgresql/data
    environment:
      - POSTGRES_USER=dbuser
      - POSTGRES_PASSWORD=admin2022
      - POSTGRES_DB=foxapp